### ISSUE TITLE
Composition and argument order: pipe ok, compose errors

### ISSUE THREAD

**Issue by wip0** [types/npm-ramda#92]
```
const x = R.cond([
  [R.F, R.F],
  [R.T, R.identity]
]);

const y = R.compose(x, R.inc);
```

If I use compose or pipe with cond function, there is an compiling error.

> Error  TS2345: Argument of type 'Function' is not assignable to parameter of type '(x0: {}, x1: {}, x2: {}) => {}'.
>   Type 'Function' provides no match for the signature '(x0: {}, x1: {}, x2: {}): {}'

at compose/pipe line.

**Comment by tycho01** [comment]
So, I think there are two things going on here; an issue with `cond`, and an issue with composition.

### `cond`:

We'd like for TS to Infer that `x` here has the `identity` type signature. This is currently problematic, in the sense that TypeScript is currently fairly ignorant with regard to values.
Take the example `let a = false ? 1 : 'a';`. TypeScript is ignorant of the `false` value, presumes both paths will be used, and infers `number | string`.
Given it fails on such basic examples, I'm not sure we can make it understand these `cond` conditions and infer which might hold true. This issue seems hard to fix for the foreseeable future.

### composition:

Let's say we work around the above issue and help it with `x` here, by manually annotating it as `<T>(v: T) => T`.
At this point, `compose` should fill in the blanks in terms of connecting `number => number` and `T => T` into `number => number`. It seems to fail at this however, by evaluating the second function's signature before passing in any `number` info, losing the info on generic `T` and retyping it as `{} => {}`. At this point, it concludes the resulting function to be typed `number => {}`.

This issue is pretty important, and sounds similar to issues with generics in the context of currying brought up [here](https://github.com/donnut/typescript-ramda/issues/78). I don't have a solution yet, but hopefully we can figure something out.

**Comment by tycho01** [comment]
I just realized the definitions for regular/promise versions of pipe/compose are returning curried functions, while they shouldn't. I now fixed that.

This hasn't actually fixed the root cause here. I'm inclined to think though that the actual cause here mirrors the problem in the issue above. Based on that, let's stick to that thread for the moment; we can reopen this if they turn out different after all.

Thank you for bringing this up!

**Comment by tycho01** [comment]
I've done an odd find -- inference appears to depend on parameter order. Consider the following contrast:
```ts
// can't infer cond paths, must annotate:
const x: <T>(v: T) => T = R.cond([
    [R.F, R.F],
    [R.T, R.identity]
]);
// argument order matters for some reason...
const y: (v: number) => number = R.pipe   (R.inc, x); // ok
const z: (v: number) => number = R.compose(x, R.inc); // boom
```
This is super weird. `pipe` and `compose` are identical in their type definitions other than having their params flipped.

Apparently `pipe` is safer than `compose`...

**Comment by tycho01** [comment]
Closing as a TypeScript limitation, see https://github.com/Microsoft/TypeScript/issues/15680#issuecomment-307571917. Added to the readme to inform users.

**Comment by tycho01** [comment]
Actually, in new TS `compose` now works as well/so-so as `pipe`. Not sure from which version exactly though, but eventually we may wanna remove this from the readme. @ikatyang

**Comment by ikatyang** [comment]
I could still reproduce the issue in TS 2.8-rc, did I miss something?

![image](https://user-images.githubusercontent.com/8341033/37567176-2508151e-2afe-11e8-953f-bfb9b45ebe8b.png)

**Comment by tycho01** [comment]
Okay, guess I'm gonna have to figure out where it did work then... weird.
